//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.24 at 04:53:20 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/donat",
xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "donat",
   namespaceURI = "http://www.sat.gob.mx/donat")},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package Core.FirmasElectronicas.complementos.donatarias;
