//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.03 at 11:43:49 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/cfd/2",
xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "",
   namespaceURI = "http://www.sat.gob.mx/cfd/2")},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package Core.FirmasElectronicas.SAT22;
