//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 04:50:56 PM CDT 
//


package Core.FirmasElectronicas.SAT_MABE;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Mabe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Mabe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Factura }
     * 
     */
    public Factura createFactura() {
        return new Factura();
    }

    /**
     * Create an instance of {@link Factura.Retenciones }
     * 
     */
    public Factura.Retenciones createFacturaRetenciones() {
        return new Factura.Retenciones();
    }

    /**
     * Create an instance of {@link Factura.Traslados }
     * 
     */
    public Factura.Traslados createFacturaTraslados() {
        return new Factura.Traslados();
    }

    /**
     * Create an instance of {@link Factura.Detalles }
     * 
     */
    public Factura.Detalles createFacturaDetalles() {
        return new Factura.Detalles();
    }

    /**
     * Create an instance of {@link Factura.Moneda }
     * 
     */
    public Factura.Moneda createFacturaMoneda() {
        return new Factura.Moneda();
    }

    /**
     * Create an instance of {@link Factura.Proveedor }
     * 
     */
    public Factura.Proveedor createFacturaProveedor() {
        return new Factura.Proveedor();
    }

    /**
     * Create an instance of {@link Factura.Entrega }
     * 
     */
    public Factura.Entrega createFacturaEntrega() {
        return new Factura.Entrega();
    }

    /**
     * Create an instance of {@link Factura.Descuentos }
     * 
     */
    public Factura.Descuentos createFacturaDescuentos() {
        return new Factura.Descuentos();
    }

    /**
     * Create an instance of {@link Factura.Subtotal }
     * 
     */
    public Factura.Subtotal createFacturaSubtotal() {
        return new Factura.Subtotal();
    }

    /**
     * Create an instance of {@link Factura.Total }
     * 
     */
    public Factura.Total createFacturaTotal() {
        return new Factura.Total();
    }

    /**
     * Create an instance of {@link Factura.Retenciones.Retencion }
     * 
     */
    public Factura.Retenciones.Retencion createFacturaRetencionesRetencion() {
        return new Factura.Retenciones.Retencion();
    }

    /**
     * Create an instance of {@link Factura.Traslados.Traslado }
     * 
     */
    public Factura.Traslados.Traslado createFacturaTrasladosTraslado() {
        return new Factura.Traslados.Traslado();
    }

    /**
     * Create an instance of {@link Factura.Detalles.Detalle }
     * 
     */
    public Factura.Detalles.Detalle createFacturaDetallesDetalle() {
        return new Factura.Detalles.Detalle();
    }

}
