//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.19 at 04:50:56 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://recepcionfe.mabempresa.com/cfd/addenda/v1",
xmlns = { @javax.xml.bind.annotation.XmlNs( prefix = "mabe",
                  namespaceURI = "http://recepcionfe.mabempresa.com/cfd/addenda/v1" )
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Core.FirmasElectronicas.SAT_MABE;

