//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:15:04 PM CDT 
//


package Core.FirmasElectronicas.Addendas.santander;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mx.siweb.addendas.santander package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddendaSantanderV1_QNAME = new QName("http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1", "AddendaSantanderV1");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mx.siweb.addendas.santander
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TInformacionPago }
     * 
     */
    public TInformacionPago createTInformacionPago() {
        return new TInformacionPago();
    }

    /**
     * Create an instance of {@link TInformacionEmision }
     * 
     */
    public TInformacionEmision createTInformacionEmision() {
        return new TInformacionEmision();
    }

    /**
     * Create an instance of {@link TBasilea }
     * 
     */
    public TBasilea createTBasilea() {
        return new TBasilea();
    }

    /**
     * Create an instance of {@link TCampoAdicional }
     * 
     */
    public TCampoAdicional createTCampoAdicional() {
        return new TCampoAdicional();
    }

    /**
     * Create an instance of {@link TInmuebles }
     * 
     */
    public TInmuebles createTInmuebles() {
        return new TInmuebles();
    }

    /**
     * Create an instance of {@link TFactoraje }
     * 
     */
    public TFactoraje createTFactoraje() {
        return new TFactoraje();
    }

    /**
     * Create an instance of {@link TAddendaSantanderV1 }
     * 
     */
    public TAddendaSantanderV1 createTAddendaSantanderV1() {
        return new TAddendaSantanderV1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAddendaSantanderV1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1", name = "AddendaSantanderV1")
    public JAXBElement<TAddendaSantanderV1> createAddendaSantanderV1(TAddendaSantanderV1 value) {
        return new JAXBElement<TAddendaSantanderV1>(_AddendaSantanderV1_QNAME, TAddendaSantanderV1 .class, null, value);
    }

}
