//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:15:04 PM CDT 
//


package Core.FirmasElectronicas.Addendas.santander;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo para elemento ra�z.
 * 
 * <p>Java class for TAddendaSantanderV1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAddendaSantanderV1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InformacionPago" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TInformacionPago" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InformacionEmision" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TInformacionEmision" minOccurs="0"/>
 *         &lt;element name="Inmuebles" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TInmuebles" minOccurs="0"/>
 *         &lt;element name="Basilea" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TBasilea" minOccurs="0"/>
 *         &lt;element name="CampoAdicional" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TCampoAdicional" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAddendaSantanderV1", propOrder = {
    "informacionPago",
    "informacionEmision",
    "inmuebles",
    "basilea",
    "campoAdicional"
})
public class TAddendaSantanderV1 {

    @XmlElement(name = "InformacionPago")
    protected List<TInformacionPago> informacionPago;
    @XmlElement(name = "InformacionEmision")
    protected TInformacionEmision informacionEmision;
    @XmlElement(name = "Inmuebles")
    protected TInmuebles inmuebles;
    @XmlElement(name = "Basilea")
    protected TBasilea basilea;
    @XmlElement(name = "CampoAdicional")
    protected List<TCampoAdicional> campoAdicional;

    /**
     * Gets the value of the informacionPago property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informacionPago property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformacionPago().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInformacionPago }
     * 
     * 
     */
    public List<TInformacionPago> getInformacionPago() {
        if (informacionPago == null) {
            informacionPago = new ArrayList<TInformacionPago>();
        }
        return this.informacionPago;
    }

    /**
     * Gets the value of the informacionEmision property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacionEmision }
     *     
     */
    public TInformacionEmision getInformacionEmision() {
        return informacionEmision;
    }

    /**
     * Sets the value of the informacionEmision property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacionEmision }
     *     
     */
    public void setInformacionEmision(TInformacionEmision value) {
        this.informacionEmision = value;
    }

    /**
     * Gets the value of the inmuebles property.
     * 
     * @return
     *     possible object is
     *     {@link TInmuebles }
     *     
     */
    public TInmuebles getInmuebles() {
        return inmuebles;
    }

    /**
     * Sets the value of the inmuebles property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInmuebles }
     *     
     */
    public void setInmuebles(TInmuebles value) {
        this.inmuebles = value;
    }

    /**
     * Gets the value of the basilea property.
     * 
     * @return
     *     possible object is
     *     {@link TBasilea }
     *     
     */
    public TBasilea getBasilea() {
        return basilea;
    }

    /**
     * Sets the value of the basilea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBasilea }
     *     
     */
    public void setBasilea(TBasilea value) {
        this.basilea = value;
    }

    /**
     * Gets the value of the campoAdicional property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the campoAdicional property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCampoAdicional().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TCampoAdicional }
     * 
     * 
     */
    public List<TCampoAdicional> getCampoAdicional() {
        if (campoAdicional == null) {
            campoAdicional = new ArrayList<TCampoAdicional>();
        }
        return this.campoAdicional;
    }

}
