//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:15:04 PM CDT 
//


package Core.FirmasElectronicas.Addendas.santander;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Estructura para los campos de Basilea.
 * 
 * <p>Java class for TBasilea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TBasilea">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="numContrato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OrigenGasto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TipoGasto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBasilea")
public class TBasilea {

    @XmlAttribute(name = "numContrato")
    protected String numContrato;
    @XmlAttribute(name = "OrigenGasto")
    protected String origenGasto;
    @XmlAttribute(name = "TipoGasto")
    protected String tipoGasto;

    /**
     * Gets the value of the numContrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumContrato() {
        return numContrato;
    }

    /**
     * Sets the value of the numContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumContrato(String value) {
        this.numContrato = value;
    }

    /**
     * Gets the value of the origenGasto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigenGasto() {
        return origenGasto;
    }

    /**
     * Sets the value of the origenGasto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigenGasto(String value) {
        this.origenGasto = value;
    }

    /**
     * Gets the value of the tipoGasto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoGasto() {
        return tipoGasto;
    }

    /**
     * Sets the value of the tipoGasto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoGasto(String value) {
        this.tipoGasto = value;
    }

}
