//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:15:04 PM CDT 
//


package Core.FirmasElectronicas.Addendas.santander;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo para representar informaci�n adicional de conceptos para Factoraje
 * 
 * <p>Java class for TFactoraje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TFactoraje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="deudorProveedor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="numeroDocumento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="plazo" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TDecimalFactoraje" />
 *       &lt;attribute name="valorNominal" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TDecimalFactoraje" />
 *       &lt;attribute name="aforo" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TDecimalFactoraje" />
 *       &lt;attribute name="precioBase" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TDecimalFactoraje" />
 *       &lt;attribute name="tasaDescuento" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TDecimalFactoraje" />
 *       &lt;attribute name="precioFactoraje" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TDecimalFactoraje" />
 *       &lt;attribute name="importeDescuento" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TDecimalFactoraje" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TFactoraje")
public class TFactoraje {

    @XmlAttribute(name = "deudorProveedor")
    protected String deudorProveedor;
    @XmlAttribute(name = "tipoDocumento")
    protected String tipoDocumento;
    @XmlAttribute(name = "numeroDocumento")
    protected String numeroDocumento;
    @XmlAttribute(name = "fechaVencimiento")
    protected String fechaVencimiento;
    @XmlAttribute(name = "plazo")
    protected BigDecimal plazo;
    @XmlAttribute(name = "valorNominal")
    protected BigDecimal valorNominal;
    @XmlAttribute(name = "aforo")
    protected BigDecimal aforo;
    @XmlAttribute(name = "precioBase")
    protected BigDecimal precioBase;
    @XmlAttribute(name = "tasaDescuento")
    protected BigDecimal tasaDescuento;
    @XmlAttribute(name = "precioFactoraje")
    protected BigDecimal precioFactoraje;
    @XmlAttribute(name = "importeDescuento")
    protected BigDecimal importeDescuento;

    /**
     * Gets the value of the deudorProveedor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeudorProveedor() {
        return deudorProveedor;
    }

    /**
     * Sets the value of the deudorProveedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeudorProveedor(String value) {
        this.deudorProveedor = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

    /**
     * Gets the value of the numeroDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroDocumento() {
        return numeroDocumento;
    }

    /**
     * Sets the value of the numeroDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroDocumento(String value) {
        this.numeroDocumento = value;
    }

    /**
     * Gets the value of the fechaVencimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * Sets the value of the fechaVencimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaVencimiento(String value) {
        this.fechaVencimiento = value;
    }

    /**
     * Gets the value of the plazo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPlazo() {
        return plazo;
    }

    /**
     * Sets the value of the plazo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPlazo(BigDecimal value) {
        this.plazo = value;
    }

    /**
     * Gets the value of the valorNominal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorNominal() {
        return valorNominal;
    }

    /**
     * Sets the value of the valorNominal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorNominal(BigDecimal value) {
        this.valorNominal = value;
    }

    /**
     * Gets the value of the aforo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAforo() {
        return aforo;
    }

    /**
     * Sets the value of the aforo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAforo(BigDecimal value) {
        this.aforo = value;
    }

    /**
     * Gets the value of the precioBase property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrecioBase() {
        return precioBase;
    }

    /**
     * Sets the value of the precioBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrecioBase(BigDecimal value) {
        this.precioBase = value;
    }

    /**
     * Gets the value of the tasaDescuento property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTasaDescuento() {
        return tasaDescuento;
    }

    /**
     * Sets the value of the tasaDescuento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTasaDescuento(BigDecimal value) {
        this.tasaDescuento = value;
    }

    /**
     * Gets the value of the precioFactoraje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrecioFactoraje() {
        return precioFactoraje;
    }

    /**
     * Sets the value of the precioFactoraje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrecioFactoraje(BigDecimal value) {
        this.precioFactoraje = value;
    }

    /**
     * Gets the value of the importeDescuento property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporteDescuento() {
        return importeDescuento;
    }

    /**
     * Sets the value of the importeDescuento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporteDescuento(BigDecimal value) {
        this.importeDescuento = value;
    }

}
