//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:15:04 PM CDT 
//


package Core.FirmasElectronicas.Addendas.santander;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo para Informaci�n de Pago.
 * 
 * <p>Java class for TInformacionPago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TInformacionPago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="numProveedor" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ordenCompra" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="posCompra" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nombreBeneficiario" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="institucionReceptora" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="numeroCuenta" use="required" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TNumeroCuenta" />
 *       &lt;attribute name="cuentaContable" type="{http://www.santander.com.mx/schemas/xsd/AddendaSantanderV1}TNumeroCuenta" />
 *       &lt;attribute name="claveDeposito" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="email" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codigoISOMoneda" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="concepto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInformacionPago")
public class TInformacionPago {

    @XmlAttribute(name = "numProveedor", required = true)
    protected String numProveedor;
    @XmlAttribute(name = "ordenCompra", required = true)
    protected String ordenCompra;
    @XmlAttribute(name = "posCompra")
    protected String posCompra;
    @XmlAttribute(name = "nombreBeneficiario", required = true)
    protected String nombreBeneficiario;
    @XmlAttribute(name = "institucionReceptora", required = true)
    protected String institucionReceptora;
    @XmlAttribute(name = "numeroCuenta", required = true)
    protected String numeroCuenta;
    @XmlAttribute(name = "cuentaContable")
    protected String cuentaContable;
    @XmlAttribute(name = "claveDeposito")
    protected String claveDeposito;
    @XmlAttribute(name = "email")
    protected String email;
    @XmlAttribute(name = "codigoISOMoneda")
    protected String codigoISOMoneda;
    @XmlAttribute(name = "concepto")
    protected String concepto;

    /**
     * Gets the value of the numProveedor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumProveedor() {
        return numProveedor;
    }

    /**
     * Sets the value of the numProveedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumProveedor(String value) {
        this.numProveedor = value;
    }

    /**
     * Gets the value of the ordenCompra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdenCompra() {
        return ordenCompra;
    }

    /**
     * Sets the value of the ordenCompra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdenCompra(String value) {
        this.ordenCompra = value;
    }

    /**
     * Gets the value of the posCompra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosCompra() {
        return posCompra;
    }

    /**
     * Sets the value of the posCompra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosCompra(String value) {
        this.posCompra = value;
    }

    /**
     * Gets the value of the nombreBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreBeneficiario() {
        return nombreBeneficiario;
    }

    /**
     * Sets the value of the nombreBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreBeneficiario(String value) {
        this.nombreBeneficiario = value;
    }

    /**
     * Gets the value of the institucionReceptora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitucionReceptora() {
        return institucionReceptora;
    }

    /**
     * Sets the value of the institucionReceptora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitucionReceptora(String value) {
        this.institucionReceptora = value;
    }

    /**
     * Gets the value of the numeroCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCuenta() {
        return numeroCuenta;
    }

    /**
     * Sets the value of the numeroCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroCuenta(String value) {
        this.numeroCuenta = value;
    }

    /**
     * Gets the value of the cuentaContable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuentaContable() {
        return cuentaContable;
    }

    /**
     * Sets the value of the cuentaContable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuentaContable(String value) {
        this.cuentaContable = value;
    }

    /**
     * Gets the value of the claveDeposito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveDeposito() {
        return claveDeposito;
    }

    /**
     * Sets the value of the claveDeposito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveDeposito(String value) {
        this.claveDeposito = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the codigoISOMoneda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoISOMoneda() {
        return codigoISOMoneda;
    }

    /**
     * Sets the value of the codigoISOMoneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoISOMoneda(String value) {
        this.codigoISOMoneda = value;
    }

    /**
     * Gets the value of the concepto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcepto() {
        return concepto;
    }

    /**
     * Sets the value of the concepto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcepto(String value) {
        this.concepto = value;
    }

}
