//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.23 at 11:09:20 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.itcomplements.com/printweb",
xmlns = { @javax.xml.bind.annotation.XmlNs( prefix = "Sonoco",
                  namespaceURI = "http://www.itcomplements.com/printweb" ),
        @javax.xml.bind.annotation.XmlNs(prefix="xs",
                   namespaceURI="http://www.w3.org/2001/XMLSchema") },
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.itcomplements.com/printweb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Core.FirmasElectronicas.SAT_SONOCO;
