//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.29 at 06:29:03 AM CST 
//Anadimos el atributo prefix para poner el prefijo cfdi

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.sat.gob.mx/cfd/3", 
        xmlns = {  
          @javax.xml.bind.annotation.XmlNs(prefix = "cfdi", namespaceURI = "http://www.sat.gob.mx/cfd/3")  
            },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Core.FirmasElectronicas.SAT3_2;
