//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.02 at 02:31:01 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/cfd/2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Core.FirmasElectronicas.SAT;
