//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.16 at 09:55:23 PM CST 
//


package Core.FirmasElectronicas.SAT_AMECE;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.siweb.addendas.SAT_AMECE package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ComprobanteAddendaRequestForPaymentSpecialInstructionText_QNAME = new QName("http://www.sat.gob.mx/cfd/3", "text");
    private final static QName _ComprobanteAddendaRequestForPaymentShipToNameAndAddressCity_QNAME = new QName("http://www.sat.gob.mx/cfd/3", "city");
    private final static QName _ComprobanteAddendaRequestForPaymentShipToNameAndAddressPostalCode_QNAME = new QName("http://www.sat.gob.mx/cfd/3", "postalCode");
    private final static QName _ComprobanteAddendaRequestForPaymentShipToNameAndAddressName_QNAME = new QName("http://www.sat.gob.mx/cfd/3", "name");
    private final static QName _ComprobanteAddendaRequestForPaymentShipToNameAndAddressStreetAddressOne_QNAME = new QName("http://www.sat.gob.mx/cfd/3", "streetAddressOne");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.siweb.addendas.SAT_AMECE
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.AdditionalInformation.ReferenceIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.AdditionalInformation.ReferenceIdentification createComprobanteAddendaRequestForPaymentAdditionalInformationReferenceIdentification() {
        return new Comprobante.Addenda.RequestForPayment.AdditionalInformation.ReferenceIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.DeliveryNote }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.DeliveryNote createComprobanteAddendaRequestForPaymentDeliveryNote() {
        return new Comprobante.Addenda.RequestForPayment.DeliveryNote();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.Customs }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.Customs createComprobanteAddendaRequestForPaymentLineItemCustoms() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.Customs();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.InvoiceCreator.NameAndAddress }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.InvoiceCreator.NameAndAddress createComprobanteAddendaRequestForPaymentInvoiceCreatorNameAndAddress() {
        return new Comprobante.Addenda.RequestForPayment.InvoiceCreator.NameAndAddress();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.InvoicedQuantity }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.InvoicedQuantity createComprobanteAddendaRequestForPaymentLineItemInvoicedQuantity() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.InvoicedQuantity();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation.Transport }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation.Transport createComprobanteAddendaRequestForPaymentLineItemPalletInformationTransport() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation.Transport();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage createComprobanteAddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentage() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.PaymentTerms }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.PaymentTerms createComprobanteAddendaRequestForPaymentPaymentTerms() {
        return new Comprobante.Addenda.RequestForPayment.PaymentTerms();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.TotalAmount }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.TotalAmount createComprobanteAddendaRequestForPaymentTotalAmount() {
        return new Comprobante.Addenda.RequestForPayment.TotalAmount();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage.RatePerUnit }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage.RatePerUnit createComprobanteAddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentageRatePerUnit() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage.RatePerUnit();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Tax }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Tax createComprobanteAddendaRequestForPaymentTax() {
        return new Comprobante.Addenda.RequestForPayment.Tax();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.Customs.AlternatePartyIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.Customs.AlternatePartyIdentification createComprobanteAddendaRequestForPaymentLineItemCustomsAlternatePartyIdentification() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.Customs.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.ExtendedAttributes.LotNumber }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.ExtendedAttributes.LotNumber createComprobanteAddendaRequestForPaymentLineItemExtendedAttributesLotNumber() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.ExtendedAttributes.LotNumber();
    }

    /**
     * Create an instance of {@link Comprobante }
     * 
     */
    public Comprobante createComprobante() {
        return new Comprobante();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos }
     * 
     */
    public Comprobante.Impuestos createComprobanteImpuestos() {
        return new Comprobante.Impuestos();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem createComprobanteAddendaRequestForPaymentLineItem() {
        return new Comprobante.Addenda.RequestForPayment.LineItem();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Buyer.ContactInformation }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Buyer.ContactInformation createComprobanteAddendaRequestForPaymentBuyerContactInformation() {
        return new Comprobante.Addenda.RequestForPayment.Buyer.ContactInformation();
    }

    /**
     * Create an instance of {@link TInformacionAduanera }
     * 
     */
    public TInformacionAduanera createTInformacionAduanera() {
        return new TInformacionAduanera();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.AdditionalInformation.ReferenceIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.AdditionalInformation.ReferenceIdentification createComprobanteAddendaRequestForPaymentLineItemAdditionalInformationReferenceIdentification() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.AdditionalInformation.ReferenceIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.NetPrice }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.NetPrice createComprobanteAddendaRequestForPaymentLineItemNetPrice() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.NetPrice();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.TradeItemTaxInformation }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.TradeItemTaxInformation createComprobanteAddendaRequestForPaymentLineItemTradeItemTaxInformation() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.TradeItemTaxInformation();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto }
     * 
     */
    public Comprobante.Conceptos.Concepto createComprobanteConceptosConcepto() {
        return new Comprobante.Conceptos.Concepto();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.InvoiceCreator.AlternatePartyIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.InvoiceCreator.AlternatePartyIdentification createComprobanteAddendaRequestForPaymentInvoiceCreatorAlternatePartyIdentification() {
        return new Comprobante.Addenda.RequestForPayment.InvoiceCreator.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.AditionalQuantity }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.AditionalQuantity createComprobanteAddendaRequestForPaymentLineItemAditionalQuantity() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.AditionalQuantity();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.AdditionalInformation }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.AdditionalInformation createComprobanteAddendaRequestForPaymentLineItemAdditionalInformation() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.AdditionalInformation();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod createComprobanteAddendaRequestForPaymentPaymentTermsNetPaymentPaymentTimePeriod() {
        return new Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Buyer.ContactInformation.PersonOrDepartmentName }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Buyer.ContactInformation.PersonOrDepartmentName createComprobanteAddendaRequestForPaymentBuyerContactInformationPersonOrDepartmentName() {
        return new Comprobante.Addenda.RequestForPayment.Buyer.ContactInformation.PersonOrDepartmentName();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.ExtendedAttributes }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.ExtendedAttributes createComprobanteAddendaRequestForPaymentLineItemExtendedAttributes() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.ExtendedAttributes();
    }

    /**
     * Create an instance of {@link Comprobante.Complemento }
     * 
     */
    public Comprobante.Complemento createComprobanteComplemento() {
        return new Comprobante.Complemento();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.LogisticUnits.SerialShippingContainerCode }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.LogisticUnits.SerialShippingContainerCode createComprobanteAddendaRequestForPaymentLineItemLogisticUnitsSerialShippingContainerCode() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.LogisticUnits.SerialShippingContainerCode();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.TotalAllowanceCharge }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.TotalAllowanceCharge createComprobanteAddendaRequestForPaymentTotalAllowanceCharge() {
        return new Comprobante.Addenda.RequestForPayment.TotalAllowanceCharge();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Customs }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Customs createComprobanteAddendaRequestForPaymentCustoms() {
        return new Comprobante.Addenda.RequestForPayment.Customs();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.AdditionalInformation }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.AdditionalInformation createComprobanteAddendaRequestForPaymentAdditionalInformation() {
        return new Comprobante.Addenda.RequestForPayment.AdditionalInformation();
    }

    /**
     * Create an instance of {@link Comprobante.Emisor }
     * 
     */
    public Comprobante.Emisor createComprobanteEmisor() {
        return new Comprobante.Emisor();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.Customs.NameAndAddress }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.Customs.NameAndAddress createComprobanteAddendaRequestForPaymentLineItemCustomsNameAndAddress() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.Customs.NameAndAddress();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount createComprobanteAddendaRequestForPaymentLineItemTotalLineAmount() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos }
     * 
     */
    public Comprobante.Conceptos createComprobanteConceptos() {
        return new Comprobante.Conceptos();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment createComprobanteAddendaRequestForPaymentPaymentTermsNetPayment() {
        return new Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.GrossPrice }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.GrossPrice createComprobanteAddendaRequestForPaymentLineItemGrossPrice() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.GrossPrice();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.OrderIdentification.ReferenceIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.OrderIdentification.ReferenceIdentification createComprobanteAddendaRequestForPaymentOrderIdentificationReferenceIdentification() {
        return new Comprobante.Addenda.RequestForPayment.OrderIdentification.ReferenceIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation createComprobanteAddendaRequestForPaymentLineItemPalletInformation() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto.Parte }
     * 
     */
    public Comprobante.Conceptos.Concepto.Parte createComprobanteConceptosConceptoParte() {
        return new Comprobante.Conceptos.Concepto.Parte();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Customs.NameAndAddress }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Customs.NameAndAddress createComprobanteAddendaRequestForPaymentCustomsNameAndAddress() {
        return new Comprobante.Addenda.RequestForPayment.Customs.NameAndAddress();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge createComprobanteAddendaRequestForPaymentLineItemAllowanceCharge() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.AllowanceCharge();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Retenciones }
     * 
     */
    public Comprobante.Impuestos.Retenciones createComprobanteImpuestosRetenciones() {
        return new Comprobante.Impuestos.Retenciones();
    }

    /**
     * Create an instance of {@link Comprobante.Emisor.RegimenFiscal }
     * 
     */
    public Comprobante.Emisor.RegimenFiscal createComprobanteEmisorRegimenFiscal() {
        return new Comprobante.Emisor.RegimenFiscal();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Seller }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Seller createComprobanteAddendaRequestForPaymentSeller() {
        return new Comprobante.Addenda.RequestForPayment.Seller();
    }

    /**
     * Create an instance of {@link Comprobante.Receptor }
     * 
     */
    public Comprobante.Receptor createComprobanteReceptor() {
        return new Comprobante.Receptor();
    }

    /**
     * Create an instance of {@link TUbicacion }
     * 
     */
    public TUbicacion createTUbicacion() {
        return new TUbicacion();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod.TimePeriodDue }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod.TimePeriodDue createComprobanteAddendaRequestForPaymentPaymentTermsNetPaymentPaymentTimePeriodTimePeriodDue() {
        return new Comprobante.Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod.TimePeriodDue();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Buyer }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Buyer createComprobanteAddendaRequestForPaymentBuyer() {
        return new Comprobante.Addenda.RequestForPayment.Buyer();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Seller.AlternatePartyIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Seller.AlternatePartyIdentification createComprobanteAddendaRequestForPaymentSellerAlternatePartyIdentification() {
        return new Comprobante.Addenda.RequestForPayment.Seller.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Currency }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Currency createComprobanteAddendaRequestForPaymentCurrency() {
        return new Comprobante.Addenda.RequestForPayment.Currency();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto.CuentaPredial }
     * 
     */
    public Comprobante.Conceptos.Concepto.CuentaPredial createComprobanteConceptosConceptoCuentaPredial() {
        return new Comprobante.Conceptos.Concepto.CuentaPredial();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage.Rate }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage.Rate createComprobanteAddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRate() {
        return new Comprobante.Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage.Rate();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.SpecialInstruction }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.SpecialInstruction createComprobanteAddendaRequestForPaymentSpecialInstruction() {
        return new Comprobante.Addenda.RequestForPayment.SpecialInstruction();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress createComprobanteAddendaRequestForPaymentShipToNameAndAddress() {
        return new Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount.GrossAmount }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount.GrossAmount createComprobanteAddendaRequestForPaymentLineItemTotalLineAmountGrossAmount() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount.GrossAmount();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.TradeItemDescriptionInformation }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.TradeItemDescriptionInformation createComprobanteAddendaRequestForPaymentLineItemTradeItemDescriptionInformation() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.TradeItemDescriptionInformation();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.OrderIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.OrderIdentification createComprobanteAddendaRequestForPaymentOrderIdentification() {
        return new Comprobante.Addenda.RequestForPayment.OrderIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation.Description }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation.Description createComprobanteAddendaRequestForPaymentLineItemPalletInformationDescription() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.PalletInformation.Description();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.PayableAmount }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.PayableAmount createComprobanteAddendaRequestForPaymentPayableAmount() {
        return new Comprobante.Addenda.RequestForPayment.PayableAmount();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto.ComplementoConcepto }
     * 
     */
    public Comprobante.Conceptos.Concepto.ComplementoConcepto createComprobanteConceptosConceptoComplementoConcepto() {
        return new Comprobante.Conceptos.Concepto.ComplementoConcepto();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.RequestForPaymentIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.RequestForPaymentIdentification createComprobanteAddendaRequestForPaymentRequestForPaymentIdentification() {
        return new Comprobante.Addenda.RequestForPayment.RequestForPaymentIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.ShipTo }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.ShipTo createComprobanteAddendaRequestForPaymentShipTo() {
        return new Comprobante.Addenda.RequestForPayment.ShipTo();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.PaymentTerms.DiscountPayment }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.PaymentTerms.DiscountPayment createComprobanteAddendaRequestForPaymentPaymentTermsDiscountPayment() {
        return new Comprobante.Addenda.RequestForPayment.PaymentTerms.DiscountPayment();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage createComprobanteAddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentage() {
        return new Comprobante.Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Retenciones.Retencion }
     * 
     */
    public Comprobante.Impuestos.Retenciones.Retencion createComprobanteImpuestosRetencionesRetencion() {
        return new Comprobante.Impuestos.Retenciones.Retencion();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.TradeItemTaxInformation.TradeItemTaxAmount }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.TradeItemTaxInformation.TradeItemTaxAmount createComprobanteAddendaRequestForPaymentLineItemTradeItemTaxInformationTradeItemTaxAmount() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.TradeItemTaxInformation.TradeItemTaxAmount();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.AllowanceCharge }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.AllowanceCharge createComprobanteAddendaRequestForPaymentAllowanceCharge() {
        return new Comprobante.Addenda.RequestForPayment.AllowanceCharge();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.Customs.AlternatePartyIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.Customs.AlternatePartyIdentification createComprobanteAddendaRequestForPaymentCustomsAlternatePartyIdentification() {
        return new Comprobante.Addenda.RequestForPayment.Customs.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Traslados.Traslado }
     * 
     */
    public Comprobante.Impuestos.Traslados.Traslado createComprobanteImpuestosTrasladosTraslado() {
        return new Comprobante.Impuestos.Traslados.Traslado();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount.NetAmount }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount.NetAmount createComprobanteAddendaRequestForPaymentLineItemTotalLineAmountNetAmount() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.TotalLineAmount.NetAmount();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.InvoiceCreator }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.InvoiceCreator createComprobanteAddendaRequestForPaymentInvoiceCreator() {
        return new Comprobante.Addenda.RequestForPayment.InvoiceCreator();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda }
     * 
     */
    public Comprobante.Addenda createComprobanteAddenda() {
        return new Comprobante.Addenda();
    }

    /**
     * Create an instance of {@link TUbicacionFiscal }
     * 
     */
    public TUbicacionFiscal createTUbicacionFiscal() {
        return new TUbicacionFiscal();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.LogisticUnits }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.LogisticUnits createComprobanteAddendaRequestForPaymentLineItemLogisticUnits() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.LogisticUnits();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Traslados }
     * 
     */
    public Comprobante.Impuestos.Traslados createComprobanteImpuestosTraslados() {
        return new Comprobante.Impuestos.Traslados();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment }
     * 
     */
    public Comprobante.Addenda.RequestForPayment createComprobanteAddendaRequestForPayment() {
        return new Comprobante.Addenda.RequestForPayment();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.BaseAmount }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.BaseAmount createComprobanteAddendaRequestForPaymentBaseAmount() {
        return new Comprobante.Addenda.RequestForPayment.BaseAmount();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.TradeItemIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.TradeItemIdentification createComprobanteAddendaRequestForPaymentLineItemTradeItemIdentification() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.TradeItemIdentification();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda.RequestForPayment.LineItem.AlternateTradeItemIdentification }
     * 
     */
    public Comprobante.Addenda.RequestForPayment.LineItem.AlternateTradeItemIdentification createComprobanteAddendaRequestForPaymentLineItemAlternateTradeItemIdentification() {
        return new Comprobante.Addenda.RequestForPayment.LineItem.AlternateTradeItemIdentification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sat.gob.mx/cfd/3", name = "text", scope = Comprobante.Addenda.RequestForPayment.SpecialInstruction.class)
    public JAXBElement<String> createComprobanteAddendaRequestForPaymentSpecialInstructionText(String value) {
        return new JAXBElement<String>(_ComprobanteAddendaRequestForPaymentSpecialInstructionText_QNAME, String.class, Comprobante.Addenda.RequestForPayment.SpecialInstruction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sat.gob.mx/cfd/3", name = "city", scope = Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createComprobanteAddendaRequestForPaymentShipToNameAndAddressCity(String value) {
        return new JAXBElement<String>(_ComprobanteAddendaRequestForPaymentShipToNameAndAddressCity_QNAME, String.class, Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sat.gob.mx/cfd/3", name = "postalCode", scope = Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createComprobanteAddendaRequestForPaymentShipToNameAndAddressPostalCode(String value) {
        return new JAXBElement<String>(_ComprobanteAddendaRequestForPaymentShipToNameAndAddressPostalCode_QNAME, String.class, Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sat.gob.mx/cfd/3", name = "name", scope = Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createComprobanteAddendaRequestForPaymentShipToNameAndAddressName(String value) {
        return new JAXBElement<String>(_ComprobanteAddendaRequestForPaymentShipToNameAndAddressName_QNAME, String.class, Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sat.gob.mx/cfd/3", name = "streetAddressOne", scope = Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createComprobanteAddendaRequestForPaymentShipToNameAndAddressStreetAddressOne(String value) {
        return new JAXBElement<String>(_ComprobanteAddendaRequestForPaymentShipToNameAndAddressStreetAddressOne_QNAME, String.class, Comprobante.Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

}
