//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.16 at 09:55:23 PM CST 
//
@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.sat.gob.mx/cfd/3", 
        xmlns = {  
          @javax.xml.bind.annotation.XmlNs(prefix = "cfdi", namespaceURI = "http://www.sat.gob.mx/cfd/3")  
            },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Core.FirmasElectronicas.SAT_AMECE;
