//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.23 at 09:55:53 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.innte.com", 
        xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "Innte",
   namespaceURI = "http://www.innte.com")},
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Core.FirmasElectronicas.Addendas.innte;
